### ISSUE TITLE
Dialog "click-outside-close" should use child element

### ISSUE THREAD

**Issue by carlos-verdes** [rossrobino/drab#34]
I see current code is using the dialog bounding rectangle to calculate if the onClick event is outside bounds, however in some cases the dialog will be fullscreen which will make break this logic.

https://github.com/rossrobino/drab/blob/b72acc2ba5e7a9f6bf97ce1af1f162f4aba5c52c/packages/drab/src/dialog/index.ts#L85

You can test your component simply adding pico css in your index.html:
```html
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.amber.min.css" />
```
In PicoCSS the modal expects an article as a child so they suggest next implementation to close when click outside:
```js
// Close with a click outside
document.addEventListener("click", (event) => {
  if (visibleModal === null) return;
  const modalContent = visibleModal.querySelector("article");
  const isClickInside = modalContent.contains(event.target);
  !isClickInside && closeModal(visibleModal);
});
```

A more generic implementation should be something like:
- if dialog top and left = 0 and width and height = viewport => get bounded rectangle from first child
- else => use current implementation

**Comment by carlos-verdes** [comment]
Extract from pico css:
```css
dialog {
    display: flex;
    z-index: 999;
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    align-items: center;
    justify-content: center;
    width: inherit;
    min-width: 100%;
    height: inherit;
    min-height: 100%;
    padding: 0;
    border: 0;
    -webkit-backdrop-filter: var(--pico-modal-overlay-backdrop-filter);
    backdrop-filter: var(--pico-modal-overlay-backdrop-filter);
    background-color: var(--pico-modal-overlay-background-color);
    color: var(--pico-color)
}
```
